### PR TITLE
feat(arcor2_kinali): add ict service 0.1.0

### PR DESCRIPTION
**Pull request by NelaMm**

### CODE REVIEW

**Comment by ZdenekM** [comment]
@NelaMm Actions now have a mandatory keyword-only parameter `an` (the change happened in https://github.com/robofit/arcor2/pull/422). An example:
```python
def test(self, serial_number: str, *, an: Optional[str] = None) -> bool:
```

**Comment by NelaMm** [comment]
@ZdenekM  Must all functions really explicitly include "an" parameter? Ec. barcode.scan() -> barcode.scan(an = None)
Is it expected Error after use barcode.scan()? 

` 
File "/home/nela/.local/lib/python3.8/site-packages/arcor2/action.py", line 110, in wrapper
    action_name = kwargs["an"]
KeyError: 'an'
`

This error is caused by the change happened in [#422](https://github.com/robofit/arcor2/pull/422) .

**Comment by ZdenekM** [comment]
Yes, all methods that are intended to be used as actions must contain that parameter. But just their definitions - you do not need to add `an=None` in the main script. All ObjectTypes were updated, including Barcode/scan: https://github.com/robofit/arcor2/blob/bbf182f2b3fff81635cf5924ae867acb8eb0146a/src/python/arcor2_kinali/object_types/barcode.py#L14 You just need to update ObjectTypes on the project service / or in already built packages.

**Comment by ZdenekM** [comment]
Another option is to not apply the `@action` decorator - by not calling `patch_object_actions` (you will just lose the ability to pause the script).

**Comment by NelaMm** [comment]
Now when I use this function without parameter ` and=None `, is thrown this KeyError.

**Comment by ZdenekM** [comment]
Are you trying it with a newly built package or with the already existing one? You might need to update `barcode.py` in the package.

**Comment by NelaMm** [comment]
I used this service in script next to folder object_types - locally downloaded.

**Comment by ZdenekM** [comment]
You need to update the content of object_types folder.

**Comment by NelaMm** [comment]
Content of object_types folder is downloaded from master - arcor2/src/python/arcor2_kinali.

**Comment by ZdenekM** [comment]
Ok, looks like a bug. I will investigate it.

**Comment by NelaMm** [comment]
I found that when I write new script and use this object it work, but when I run script that use else script that use this object it crash.

**Comment by NelaMm** [comment]
After removing of use the function `patch_object_actions` it seems to behave correctly.

**Comment by ZdenekM** [comment]
Should be fixed by https://github.com/robofit/arcor2/pull/440.

**Pull request merged**
